apiVersion: v2
name: leitwerk
version: 0.1.3 # x-release-please-version
appVersion: "0.1.3" # x-release-please-version
description: Helm chart for the leitwerk singleton server and Kubernetes worker runner
home: https://github.com/leitwerk-dev/leitwerk
sources:
  - https://github.com/leitwerk-dev/leitwerk
type: application
