export const WORKER_INSTANCE_ID_ENV = "LEITWERK_INSTANCE_ID";
export const WORKER_ID_ENV = "LEITWERK_WORKER_ID";
export const WORKER_IPC_SERVER_URL_ENV = "LEITWERK_SERVER_URL";
export const WORKER_IPC_CONNECT_TOKEN_ENV = "LEITWERK_WORKER_CONNECT_TOKEN";
export const WORKER_IPC_RECONNECT_ENV = "LEITWERK_WORKER_RECONNECT";
export const WORKER_SNAPSHOT_TOKEN_ENV = "LEITWERK_WORKER_SNAPSHOT_TOKEN";
export const WORKER_SERVER_EPOCH_ENV = "LEITWERK_SERVER_EPOCH";
