import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parseArgs } from "node:util";
import { preserveDeclarationAnnotations } from "./api-declarations.js";
import {
	type ApiPackage,
	type ApiSurface,
	apiPackages,
	apiProgram,
	apiSurface,
} from "./api-surface.js";

export function classificationDiagnostics(surface: ApiSurface): string[] {
	const diagnostics = [...surface.diagnostics];
	for (const item of surface.items) {
		if (!item.tags.length) diagnostics.push(`${item.id}: missing @public or @internal`);
		if (new Set(item.tags).size > 1)
			diagnostics.push(`${item.id}: conflicting @public and @internal`);
		if (!item.tags.includes("public")) continue;
		for (const dependency of [...item.dependencies, ...(item.parent ? [item.parent] : [])])
			if (!dependency.tags.includes("public"))
				diagnostics.push(`${item.id}: supported signature depends on internal ${dependency.id}`);
	}
	return diagnostics;
}

export function interfaceReport(surface: ApiSurface, pkg: ApiPackage): string {
	const entries = [...surface.exports]
		.filter(([key]) => key.startsWith(`${pkg.name}#`) || key.startsWith(`${pkg.name}/`))
		.map(
			([key, items]) =>
				`- \`${key}\` → ${items.map((i) => `\`${i.id}\``).join(", ") || "external dependency"}`,
		);
	return [
		`# ${pkg.name}`,
		"",
		"Generated by `leitwerk-dev api:check --update`. Review classification and signature changes.",
		"",
		"## Entry points",
		"",
		...entries.sort(),
		"",
		"## Declarations and members",
		"",
		...surface.items
			.filter((item) => item.package === pkg)
			.sort((a, b) => a.id.localeCompare(b.id))
			.flatMap((item) => [
				`### ${item.id}`,
				"",
				`@${item.tags.join(" @") || "unclassified"}`,
				"",
				"```ts",
				item.signature,
				"```",
				"",
			]),
	].join("\n");
}

export function checkApi(root: string, update = false): string[] {
	const packages = apiPackages(root);
	if (!packages.length)
		return [
			"No typed package entry points found; add package.json exports with source or types conditions.",
		];
	const surface = apiSurface(apiProgram(packages), packages);
	const diagnostics = classificationDiagnostics(surface);
	if (diagnostics.length) return diagnostics;
	const dir = path.join(root, "api-reports");
	const expected = new Set<string>();
	for (const pkg of packages) {
		const report = interfaceReport(surface, pkg);
		const file = path.join(dir, `${pkg.name.replace(/^@/, "").replaceAll("/", "--")}.api.md`);
		expected.add(path.basename(file));
		if (update) {
			mkdirSync(dir, { recursive: true });
			writeFileSync(file, report);
		} else if (!existsSync(file) || readFileSync(file, "utf8") !== report)
			diagnostics.push(
				`${path.relative(root, file)}: interface report drift; review changes, then run leitwerk-dev api:check --workspace ${root} --update`,
			);
	}
	for (const file of existsSync(dir) ? readdirSync(dir) : []) {
		if (!file.endsWith(".api.md") || expected.has(file)) continue;
		if (update) rmSync(path.join(dir, file));
		else
			diagnostics.push(
				`${path.join("api-reports", file)}: obsolete interface report; review the removed package entry points`,
			);
	}
	return diagnostics;
}

export function runApiCheckCli(args: string[]): void {
	const { values } = parseArgs({
		args,
		options: {
			workspace: { type: "string" },
			update: { type: "boolean" },
			built: { type: "boolean" },
			help: { type: "boolean", short: "h" },
		},
	});
	if (values.help) {
		console.info(
			"Usage: leitwerk-dev api:check [--workspace PATH] [--update] [--built]\nChecks explicit release tags, supported signature dependencies and api-reports/*.api.md.\n--update writes reviewable interface reports after classification checks pass.\n--built also verifies both classifications survive declaration emission.",
		);
		return;
	}
	const root = path.resolve(values.workspace ?? process.cwd());
	const diagnostics = checkApi(root, values.update);
	if (values.built && !diagnostics.length)
		diagnostics.push(...preserveDeclarationAnnotations(root, false));
	if (diagnostics.length) throw new Error(diagnostics.join("\n"));
	console.info("API classification and interface reports are current.");
}
