export {
	buildExtensionCatalogFromModules,
	buildProcessLaunchersForTest,
	buildProcessWatchersForTest,
	buildServerProcessForTest,
	buildUiProcessForTest,
	buildWorkerProcessForTest,
	type CreateTestProcessContextOptions,
	type CreateTestServerProcessContextOptions,
	createLoadedExtensionModuleForTest,
	createTestProcessInstance,
	createTestProcessProject,
	createTestServerProcessContext,
	createTestWorkerProcessContext,
	type RunWorkerTurnForTestOptions,
	type RunWorkerTurnForTestResult,
	runWorkerProcessTurnForTest,
	runWorkerTurnForTest,
	type TestExtensionModuleOptions,
	type WorkerTurnCall,
} from "./testing.js";
